const CSS_CLASS = {
    UI: 'meditor-ui',
    UI_DRAGGING: 'meditor-ui-dragging',
    UI_HIDDEN: 'meditor-ui-hidden',
    
    SORTABLE: 'ui-sortable',
    
    WRAPPER: 'meditor-wrapper',
    
    BTN: 'meditor-btn',
    BTN_GROUP: 'meditor-btn-group',
    BTN_PRIMARY: 'meditor-btn-primary',
    BTN_DEFAULT: 'meditor-btn-default',
    
    STATE_ACTIVE: 'active',
    STATE_OPENED: 'opened',
    STATE_SHOWED: 'showed',
    STATE_SELECTED: 'selected',
    STATE_DUPLICATED: 'duplicated',
    STATE_INITIALIZED: 'initialized',
    STATE_INITIALIZING: 'initializing',
    STATE_PREVIEWING: 'previewing',
    STATE_TOOLBAR_SHOWED: 'showed-meditor-toolbar',
    STATE_MODAL_OPENED: 'opened-modal',
    STATE_NOT_MATCHED: 'not-matched',
    STATE_HAS_COMPONENT: 'has-component',
    STATE_HAS_FOOTER: 'has-footer',
    
    ADD_CONTENT: 'btn-add-content',
    
    SIDEBAR: 'meditor-sidebar',
    SIDEBAR_HEADER: 'meditor-sidebar-header',
    SIDEBAR_BODY: 'meditor-sidebar-body',
    SIDEBAR_TITLE: 'meditor-sidebar-title',
    SIDEBAR_CLOSER: 'meditor-sidebar-closer',
    
    TOPBAR: 'meditor-topbar',
    TOPBAR_LEFT: 'meditor-topbar-left',
    TOPBAR_CENTER: 'meditor-topbar-center',
    TOPBAR_RIGHT: 'meditor-topbar-right',
    TOPBAR_BUTTON: 'meditor-topbar-btn',
    TOPBAR_TITLE: 'meditor-topbar-title',
    
    MODAL: 'meditor-modal',
    MODAL_COMPONENT: 'meditor-modal-component',
    MODAL_CONTAINER: 'meditor-modal-container',
    MODAL_HEADER: 'meditor-modal-header',
    MODAL_TITLE: 'meditor-modal-title',
    MODAL_BODY: 'meditor-modal-body',
    MODAL_FOOTER: 'meditor-modal-footer',
    MODAL_CLOSE: 'meditor-modal-close',
    MODAL_ADD: 'meditor-modal-add',
    
    SNIPPET: 'meditor-snippet',
    SNIPPET_INNER: 'meditor-snippet-inner',
    SNIPPET_TITLE: 'meditor-snippet-title',
    SNIPPET_ADD: 'meditor-snippet-add',
    SNIPPET_PREVIEW: 'meditor-snippet-preview',
    SNIPPET_CONTAINER: 'meditor-snippet-container',
    SNIPPET_COMPONENT: 'meditor-snippet-component',
    SNIPPETS: 'meditor-snippets',
    SNIPPETS_FILTER: 'meditor-snippets-filter',
    SNIPPETS_FILTER_COMPONENT: 'meditor-snippets-filter-component',
    SNIPPETS_FILTER_CONTAINER: 'meditor-snippets-filter-container',
    SNIPPETS_FILTER_LABEL: 'meditor-snippets-filter-label',
    SNIPPETS_SEARCH: 'meditor-snippets-search',
    SNIPPETS_FILTER_WRAPPER: 'meditor-snippets-filter-wrapper',
    SNIPPETS_COMPONENT: 'meditor-snippets-component',
    SNIPPETS_WRAPPER: 'meditor-snippets-wrapper',
    
    TOOLBAR: 'meditor-toolbar',
    TOOLBAR_BOTTOM: 'meditor-toolbar-bottom',
    TOOLBAR_CONTENT_AREA: 'meditor-toolbar-content-area',
    TOOLBAR_CONTAINER: 'meditor-toolbar-container',
    TOOLBAR_CONTAINER_CONTENT: 'meditor-toolbar-container-content',
    TOOLBAR_SUB_CONTAINER: 'meditor-toolbar-sub-container',
    TOOLBAR_SUB_CONTAINER_BOTTOM: 'meditor-toolbar-bottom-sub-container',
    TOOLBAR_COMPONENT: 'meditor-toolbar-component',
    TOOLBAR_COMPONENT_BOTTOM: 'meditor-toolbar-bottom-component',
    
    SETTING: 'meditor-setting',
    SETTING_FORM: 'meditor-setting-form',
    SETTING_FORM_LOADING: 'meditor-setting-form-loading',
    
    CONTENT_AREA: 'meditor-content-area',
    CONTENT_AREA_INNER: 'meditor-content-area-inner',
    CONTENT_AREAS: 'meditor-content-areas',
    CONTENT_AREAS_WRAPPER: 'meditor-content-areas-wrapper',
    
    IFRAME: 'meditor-iframe',
    IFRAME_BODY: 'meditor-iframe-body',
    IFRAME_WRAPPER: 'meditor-iframe-wrapper',
    IFRAME_WIDTH_SWITCHER: 'meditor-iframe-width-switcher',
    IFRAME_COVER_WRAPPER: 'meditor-iframe-cover-wrapper',
    IFRAME_COVER_WRAPPER_FAKE: 'meditor-iframe-cover-wrapper-fake',
    IFRAME_COVER: 'meditor-iframe-cover',
    IFRAME_COVER_HIDDEN: 'hidden-cover',
    
    COMPONENT: 'meditor-component',
    COMPONENT_MOVE: 'btn-component-move',
    COMPONENT_MOVE_UP: 'btn-component-move-up',
    COMPONENT_MOVE_DOWN: 'btn-component-move-down',
    COMPONENT_SETTING: 'btn-component-setting',
    COMPONENT_DUPLICATE: 'btn-component-duplicate',
    COMPONENT_COPY: 'btn-component-copy',
    COMPONENT_CUT: 'btn-component-cut',
    COMPONENT_DELETE: 'btn-component-delete',
    COMPONENT_CONTENT: 'meditor-component-content',
    COMPONENT_EXISTING: 'existing-component',
    
    CONTAINER: 'meditor-container',
    CONTAINER_MOVE: 'btn-container-move',
    CONTAINER_MOVE_UP: 'btn-container-move-up',
    CONTAINER_MOVE_DOWN: 'btn-container-move-down',
    CONTAINER_DUPLICATE: 'btn-container-duplicate',
    CONTAINER_COPY: 'btn-container-copy',
    CONTAINER_CUT: 'btn-container-cut',
    CONTAINER_DELETE: 'btn-container-delete',
    CONTAINER_SETTING: 'btn-container-setting',
    CONTAINER_INNER: 'meditor-container-inner',
    CONTAINER_CONTENT: 'meditor-container-content',
    CONTAINER_CONTENT_INNER: 'meditor-container-content-inner',
    
    SUB_CONTAINER: 'meditor-sub-container',
    SUB_CONTAINER_CONTENT: 'meditor-sub-container-content',
    
    PREVIEW_AREA: 'meditor-preview-area',
};

export default CSS_CLASS;
